/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LinkItem = {
  _type: "linkItem";
  name: string;
  url?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform: "instagram" | "linkedin" | "behance" | "dribbble" | "twitter";
  url: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomepageItem = {
  _type: "homepageItem";
  mediaType: "image" | "gif" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  project: ProjectReference;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  categories?: string;
  client?: string;
  year?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  exhibitions?: Array<{
    year: number;
    title: string;
    _type: "exhibition";
    _key: string;
  }>;
  press?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  interviews?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  contact?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  social?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    {
      _key: string;
    } & HomepageItem
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LinkItem
  | SocialLink
  | SanityImageAssetReference
  | SanityFileAssetReference
  | ProjectReference
  | HomepageItem
  | Seo
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | About
  | Homepage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    title,    tagline,    description,    logo{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    socialLinks[]{ platform, url },  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null;
      tagline: null;
      description: null;
      logo: null;
      socialLinks: null;
    }
  | {
      title: string;
      tagline: null;
      description: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      logo: null;
      socialLinks: null;
    }
  | {
      title: string | null;
      tagline: null;
      description: string | null;
      logo: null;
      socialLinks: null;
    }
  | {
      title: string;
      tagline: string | null;
      description: string | null;
      logo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: null;
      } | null;
      socialLinks: Array<{
        platform: "behance" | "dribbble" | "instagram" | "linkedin" | "twitter";
        url: string;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]  | order(year desc) {    _id,    title,    "slug": slug.current,    client,    year,    description,    categories,    "coverImage": gallery[0]{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  client: string | null;
  year: number | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  categories: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    client,    year,    description,    categories,    gallery[]{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string;
  client: string | null;
  year: number | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  categories: string | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_id == "homepage"][0]{    items[]{      mediaType,      image{   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },      "videoUrl": video.asset->url,      project->{        title,        "slug": slug.current      }    }  }
export type HOMEPAGE_QUERY_RESULT =
  | {
      items: null;
    }
  | {
      items: Array<{
        mediaType: "gif" | "image" | "video";
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          alt: null;
        } | null;
        videoUrl: string | null;
        project: {
          title: string;
          slug: string;
        };
      }> | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_id == "about"][0]{    mainDescription,    exhibitions[]{ year, title },    press[]{ name, url },    interviews[]{ name, url },    contact,    social[]{ platform, url },  }
export type ABOUT_QUERY_RESULT =
  | {
      mainDescription: null;
      exhibitions: null;
      press: null;
      interviews: null;
      contact: null;
      social: null;
    }
  | {
      mainDescription: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      exhibitions: Array<{
        year: number;
        title: string;
      }> | null;
      press: Array<{
        name: string;
        url: string | null;
      }> | null;
      interviews: Array<{
        name: string;
        url: string | null;
      }> | null;
      contact: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      social: Array<{
        platform: "behance" | "dribbble" | "instagram" | "linkedin" | "twitter";
        url: string;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    title,\n    tagline,\n    description,\n    logo{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    socialLinks[]{ platform, url },\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]\n  | order(year desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    client,\n    year,\n    description,\n    categories,\n    "coverImage": gallery[0]{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    client,\n    year,\n    description,\n    categories,\n    gallery[]{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_id == "homepage"][0]{\n    items[]{\n      mediaType,\n      image{ \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n      "videoUrl": video.asset->url,\n      project->{\n        title,\n        "slug": slug.current\n      }\n    }\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_id == "about"][0]{\n    mainDescription,\n    exhibitions[]{ year, title },\n    press[]{ name, url },\n    interviews[]{ name, url },\n    contact,\n    social[]{ platform, url },\n  }\n': ABOUT_QUERY_RESULT;
  }
}
